import test from 'node:test';
import assert from 'node:assert/strict';
import { attachmentAccept, attachmentError, attachmentLimit, attachmentRequiresArchive } from '../src/lib/contact-rules.mjs';
import { createAttachmentArchive } from '../worker/attachment-archive.mjs';
import { encodeAttachment } from '../worker/attachments.mjs';

test('accepts requested documents, spreadsheets, Markdown and image formats regardless of case', () => {
  const requested = ['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docs', 'docx', 'dcx', 'xls', 'xlsx', 'txt', 'md', 'svg', 'gif', 'webp', 'avif', 'heic', 'heif', 'tif', 'tiff', 'bmp', 'ico', 'jp2', 'jxl', 'psd', 'exr'];
  for (const extension of requested) {
    assert.ok(attachmentAccept.split(',').includes('.' + extension));
    assert.equal(attachmentError({ name: 'brief.' + extension.toUpperCase(), size: 1 }), null);
  }
  assert.equal(attachmentError({ name: 'brief.xlxs', size: 1 }), 'fileTypeError');
  assert.equal(attachmentError({ name: 'brief.svg.exe', size: 1 }), 'fileTypeError');
  assert.equal(attachmentError({ name: '../brief.md', size: 1 }), 'fileTypeError');
  assert.equal(attachmentError({ name: 'brief.svg', size: 0 }), 'fileEmptyError');
  assert.equal(attachmentError({ name: 'brief.xlsx', size: attachmentLimit + 1 }), 'fileSizeError');
});

test('ZIP bytes match an independent Python zipfile fixture, preserving a Bengali filename and binary content', () => {
  const content = Uint8Array.from([0, 255, 10, 13, 128, 129]);
  // Generated by Python zipfile.ZIP_STORED with DOS epoch, UTF-8 name and DOS archive attribute.
  const fixture = 'UEsDBBQAAAgAAAAAIQDlPv+9BgAAAAYAAAASAAAA4Kas4Ka+4KaC4Kay4Ka+Lm1kAP8KDYCBUEsBAhQAFAAACAAAAAAhAOU+/70GAAAABgAAABIAAAAAAAAAAAAgAAAAAAAAAOCmrOCmvuCmguCmsuCmvi5tZFBLBQYAAAAAAQABAEAAAAA2AAAAAAA=';
  assert.deepEqual(Buffer.from(createAttachmentArchive('বাংলা.md', content)), Buffer.from(fixture, 'base64'));
});

test('uses ZIP for provider-unsupported formats and Unicode names, preserving the original bytes', async () => {
  const content = Uint8Array.from([0, 255, 10, 13, 128, 129]);
  for (const name of ['brief.pdf', 'brief.xlsx', 'image.JPG', 'image.tiff', 'notes.txt', 'latest screentshot.png']) {
    assert.equal(attachmentRequiresArchive(name), false);
    const encoded = await encodeAttachment(new File([content], name));
    assert.equal(encoded.name, name);
    assert.deepEqual(Buffer.from(encoded.content, 'base64'), Buffer.from(content));
  }
  const archivedNames = [
    ['বাংলা.md', 'attachment.zip'], ['বাংলা.png', 'attachment.zip'],
    ['image.SVG', 'image.SVG.zip'], ['image.dcx', 'image.dcx.zip'],
    ['image.heic', 'image.heic.zip'], ['brief.docs', 'brief.docs.zip'],
  ];
  for (const [name, deliveryName] of archivedNames) {
    assert.equal(attachmentRequiresArchive(name), true);
    const encoded = await encodeAttachment(new File([content], name));
    assert.equal(encoded.name, deliveryName);
    assert.deepEqual(Buffer.from(encoded.content, 'base64'), Buffer.from(createAttachmentArchive(name, content)));
  }
});

test('delivers a macOS screenshot filename inside an ASCII-named ZIP matching an independent fixture', async () => {
  const name = 'Screenshot 2026-10-09 at 10.41.57\u202fPM.png';
  const content = Uint8Array.from([0, 255, 10, 13, 128, 129]);
  // Python zipfile fixture uses the exact original Unicode filename and binary contents.
  const fixture = 'UEsDBBQAAAgAAAAAIQDlPv+9BgAAAAYAAAAqAAAAU2NyZWVuc2hvdCAyMDI2LTEwLTA5IGF0IDEwLjQxLjU34oCvUE0ucG5nAP8KDYCBUEsBAhQAFAAACAAAAAAhAOU+/70GAAAABgAAACoAAAAAAAAAAAAgAAAAAAAAAFNjcmVlbnNob3QgMjAyNi0xMC0wOSBhdCAxMC40MS41N+KAr1BNLnBuZ1BLBQYAAAAAAQABAFgAAABOAAAAAAA=';
  const encoded = await encodeAttachment(new File([content], name));
  assert.equal(encoded.name, 'attachment.zip');
  assert.deepEqual(Buffer.from(encoded.content, 'base64'), Buffer.from(fixture, 'base64'));
});
